apiVersion: apps/v1
kind: Deployment
metadata:
  name: optit-lab-react-deployment
  namespace: devopskubectl01
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: optit-lab-react
  template:
    metadata:
      labels:
        app: optit-lab-react
    spec:
      containers:
      - name: optit-lab-react-container
        image: bharathoptdocker/optit-lab-service:latest 
        ports:
        - containerPort: 80
