apiVersion: apps/v1
kind: Deployment
metadata:
  name: optit-lab-react-deployment
  namespace: devopskubectl01
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: optit-lab-react
  template:
    metadata:
      labels:
        app: optit-lab-react
    spec:
      containers:
      - name: optit-lab-react-container
        image: bharathoptdocker/rectjs:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: optit-lab-react-service
  namespace: devopskubectl01
spec:
  selector:
    app: optit-lab-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
